import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  content: {
    padding: 16,
    gap: 20,
    paddingBottom: 28,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
  },
  profileHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  menuButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#d4d4d4",
    backgroundColor: "#fff",
  },
  menuButtonText: {
    fontSize: 18,
    color: "#222",
    marginTop: -1,
  },
  profileHero: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#e2e2e2",
    borderRadius: 12,
    backgroundColor: "#fbfbfb",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 18,
    gap: 6,
  },
  avatarImage: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: "#eee",
  },
  avatarFallback: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: "#d9d9d9",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarFallbackText: {
    fontSize: 28,
    fontWeight: "700",
    color: "#3a3a3a",
  },
  profileName: {
    fontSize: 22,
    fontWeight: "700",
    color: "#151515",
    marginTop: 4,
  },
  profileUsername: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6a6a6a",
  },
  profileCountsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginTop: 2,
  },
  profileCountText: {
    fontSize: 13,
    color: "#5f5f5f",
    fontWeight: "600",
  },
  profileBio: {
    fontSize: 14,
    color: "#2a2a2a",
    lineHeight: 20,
    textAlign: "center",
  },
  profileLocation: {
    fontSize: 13,
    color: "#6d6d6d",
  },
  info: {
    padding: 16,
    backgroundColor: "#f5f5f5",
    borderRadius: 12,
  },
  label: {
    fontSize: 12,
    color: "#888",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 4,
  },
  email: {
    fontSize: 16,
    fontWeight: "600",
  },
  name: {
    fontSize: 14,
    color: "#666",
    marginTop: 4,
  },
  section: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#e2e2e2",
    borderRadius: 12,
    padding: 12,
    gap: 12,
    backgroundColor: "#fbfbfb",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1f1f1f",
  },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#d3d3d3",
    backgroundColor: "#fff",
  },
  inlineCreateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  inlineInput: {
    flex: 1,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#ccc",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fff",
    fontSize: 15,
  },
  multilineInput: {
    minHeight: 80,
    textAlignVertical: "top",
  },
  primaryButton: {
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: "#1f1f1f",
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
  },
  secondaryButton: {
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#ccc",
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  secondaryButtonText: {
    color: "#222",
    fontWeight: "700",
    fontSize: 14,
  },
  inlineCreateButton: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#222",
  },
  listRow: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fff",
  },
  rowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  listName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1f1f1f",
  },
  listMeta: {
    fontSize: 12,
    color: "#767676",
  },
  listInfo: {
    flex: 1,
    gap: 4,
  },
  disabledButton: {
    opacity: 0.6,
  },
  pendingText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#555",
  },
  errorText: {
    color: "#cc2a2a",
    fontSize: 13,
    lineHeight: 18,
  },
  signOutButton: {
    padding: 14,
    backgroundColor: "#ff3b30",
    borderRadius: 10,
    alignItems: "center",
  },
  signOutText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
});
