import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  flex: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#e3e3e3",
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: "#111",
  },
  closeText: {
    fontSize: 15,
    color: "#007AFF",
    fontWeight: "500",
  },
  content: {
    padding: 16,
    paddingBottom: 32,
    gap: 16,
  },
  section: {
    gap: 10,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#222",
  },
  input: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#d3d3d3",
    borderRadius: 10,
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
  },
  notesInput: {
    minHeight: 84,
    textAlignVertical: "top",
  },
  selectedShowCard: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#d3d3d3",
    borderRadius: 10,
    padding: 12,
    gap: 4,
    backgroundColor: "#f8f8ff",
  },
  selectedShowName: {
    fontSize: 17,
    fontWeight: "600",
    color: "#111",
  },
  changeShowText: {
    marginTop: 4,
    fontSize: 14,
    color: "#007AFF",
    fontWeight: "500",
  },
  resultsCard: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#e1e1e1",
    borderRadius: 10,
    overflow: "hidden",
  },
  customShowRow: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#f8f8ff",
  },
  customShowText: {
    color: "#007AFF",
    fontWeight: "500",
    fontSize: 14,
  },
  noResultsRow: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  noResultsText: {
    color: "#999",
    fontSize: 14,
  },
  suggestionHeaderRow: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#ededed",
    backgroundColor: "#fafafa",
  },
  suggestionHeaderText: {
    fontSize: 12,
    color: "#888",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  resultRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#ededed",
    gap: 8,
  },
  resultRowExactMatch: {
    backgroundColor: "#e2f3e6",
  },
  resultName: {
    fontSize: 14,
    fontWeight: "500",
    color: "#222",
  },
  resultType: {
    fontSize: 12,
    color: "#888",
  },
  resultMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  statusBadge: {
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  statusBadgeSeen: {
    backgroundColor: "#dff3ff",
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#444",
    letterSpacing: 0.25,
    textTransform: "uppercase",
  },
  statusBadgeIcon: {
    fontSize: 11,
    letterSpacing: 0,
    textTransform: "none",
  },
  productionRow: {
    gap: 8,
  },
  productionChip: {
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#cecece",
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "#fff",
  },
  productionChipSelected: {
    backgroundColor: "#007AFF",
    borderColor: "#007AFF",
  },
  productionChipText: {
    fontSize: 13,
    color: "#444",
    fontWeight: "500",
  },
  productionChipTextSelected: {
    color: "#fff",
  },
  otherForm: {
    gap: 10,
  },
  helperText: {
    fontSize: 13,
    color: "#666",
    lineHeight: 18,
  },
  keepCurrentRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#999",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  checkboxChecked: {
    backgroundColor: "#007AFF",
    borderColor: "#007AFF",
  },
  checkmark: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
  },
  keepCurrentText: {
    fontSize: 14,
    color: "#222",
    fontWeight: "500",
  },
  rankingCard: {
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#dedede",
    backgroundColor: "#fafafa",
    padding: 12,
    gap: 6,
  },
  selectedTierRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  selectedTierPill: {
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  selectedTierValue: {
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  placeholderTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
  },
  tierGrid: {
    flexDirection: "row",
    gap: 8,
  },
  tierButton: {
    flex: 1,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 10,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  tierButtonText: {
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  comparisonBlock: {
    gap: 10,
    marginTop: 4,
  },
  comparisonCards: {
    flexDirection: "row",
    gap: 10,
  },
  playbillCard: {
    flex: 1,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#d4d4d4",
    backgroundColor: "#fff",
    overflow: "hidden",
    paddingBottom: 10,
  },
  playbillImage: {
    width: "100%",
    aspectRatio: 2 / 3,
    backgroundColor: "#eee",
  },
  playbillFallback: {
    width: "100%",
    aspectRatio: 2 / 3,
    backgroundColor: "#efefef",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  playbillFallbackText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#666",
    textAlign: "center",
  },
  playbillName: {
    fontSize: 13,
    color: "#222",
    fontWeight: "600",
    paddingHorizontal: 10,
    paddingTop: 8,
  },
  resultBlock: {
    marginTop: 8,
    gap: 6,
  },
  resultText: {
    fontSize: 18,
    color: "#111",
    fontWeight: "800",
  },
  saveButton: {
    borderRadius: 12,
    backgroundColor: "#007AFF",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13,
    marginTop: 4,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
});
